// src/lib/contracts.ts
// Exposes the Sepolia address + ABI generated by Hardhat.
import Counter from '../../contracts-out/Counter.sepolia.json';

export const COUNTER_ADDRESS = (Counter as any).address as `0x${string}`;
export const COUNTER_ABI = (Counter as any).abi;
